version: '2'

services:
  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3-management
    ports:
      - "50672:5672"
      - "50673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

  consumer_1:
    restart: on-failure
    build:
      context: ./consumer
    container_name: consumer_1
    env_file: ./env/consumer/.env
    depends_on:
      - rabbit_mq

  consumer_2:
    restart: on-failure
    build:
      context: ./consumer
    container_name: consumer_2
    env_file: ./env/consumer/.env
    depends_on:
      - rabbit_mq

  consumer_3:
    restart: on-failure
    build:
      context: ./consumer
    container_name: consumer_3
    env_file: ./env/consumer/.env
    depends_on:
      - rabbit_mq

  consumer_4:
    restart: on-failure
    build:
      context: ./consumer
    container_name: consumer_4
    env_file: ./env/consumer/.env
    depends_on:
      - rabbit_mq

  producer:
    restart: on-failure
    build:
      context: ./producer
    container_name: producer
    env_file: ./env/producer/.env
    depends_on:
      - rabbit_mq